name: docker image build and push demo  
on:                           
  workflow_dispatch:   

jobs:                       
    publish_images: 
        runs-on: ubuntu-latest 

        steps:     
         - name: Checkout code  
           uses: actions/checkout@v4   
         - name:  Build and docker image 
           run: |
             docker build  -t ${{ secrets.DOCKER_HUB_USERNAME}}/github-action-project:main .
         - name: push docker images to dockerhub   
           run: |
             docker login -u ${{ secrets.DOCKER_HUB_USERNAME}} -p ${{ secrets.DOCKER_HUB_TOKEN}}
             docker push ${{ secrets.DOCKER_HUB_USERNAME}}/github-action-project:main 
